-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 18:28:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hospital` ;

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `hospital`.`suppliers` (
                                                      `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      `name` VARCHAR(45) NOT NULL,
    `country` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`equipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`equipments` ;

CREATE TABLE IF NOT EXISTS `hospital`.`equipments` (
                                                       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(45) NOT NULL,
    `price` DECIMAL(5,1) UNSIGNED NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`medications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`medications` ;

CREATE TABLE IF NOT EXISTS `hospital`.`medications` (
                                                        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(45) NOT NULL,
    `form` VARCHAR(45) NOT NULL,
    `dosage` DOUBLE UNSIGNED NULL,
    `price` DECIMAL(5,1) UNSIGNED NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`equipment_suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`equipment_suppliers` ;

CREATE TABLE IF NOT EXISTS `hospital`.`equipment_suppliers` (
                                                                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                `supplier_id` BIGINT UNSIGNED NOT NULL,
                                                                `equipment_id` BIGINT UNSIGNED NOT NULL,
                                                                INDEX `fk_Supplier_has_Equipment_Equipment1_idx` (`equipment_id` ASC) VISIBLE,
    INDEX `fk_Supplier_has_Equipment_Supplier_idx` (`supplier_id` ASC) VISIBLE,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_Supplier_has_Equipment_Supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `hospital`.`suppliers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Supplier_has_Equipment_Equipment1`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `hospital`.`equipments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`medication_suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`medication_suppliers` ;

CREATE TABLE IF NOT EXISTS `hospital`.`medication_suppliers` (
                                                                 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                 `medication_id` BIGINT UNSIGNED NOT NULL,
                                                                 `supplier_id` BIGINT UNSIGNED NOT NULL,
                                                                 INDEX `fk_medications_has_supplier_supplier1_idx` (`supplier_id` ASC) VISIBLE,
    INDEX `fk_medications_has_supplier_medications1_idx` (`medication_id` ASC) VISIBLE,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_medications_has_supplier_medications1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `hospital`.`medications` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_medications_has_supplier_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `hospital`.`suppliers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`specializations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`specializations` ;

CREATE TABLE IF NOT EXISTS `hospital`.`specializations` (
                                                            `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                            `name` VARCHAR(45) NOT NULL,
    `salary` DECIMAL(5,1) UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`addresses` ;

CREATE TABLE IF NOT EXISTS `hospital`.`addresses` (
                                                      `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      `city` VARCHAR(45) NOT NULL,
    `street` VARCHAR(45) NOT NULL,
    `building_number` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`hospitals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`hospitals` ;

CREATE TABLE IF NOT EXISTS `hospital`.`hospitals` (
                                                      `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      `title` VARCHAR(45) NOT NULL,
    `chief_doctor_id` BIGINT UNSIGNED NOT NULL,
    `address_id` BIGINT UNSIGNED NOT NULL,
    `phone_number` INT UNSIGNED NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_hospitals_employees1_idx` (`chief_doctor_id` ASC) VISIBLE,
    INDEX `fk_hospitals_addresses1_idx` (`address_id` ASC) VISIBLE,
    CONSTRAINT `fk_hospitals_employees1`
    FOREIGN KEY (`chief_doctor_id`)
    REFERENCES `hospital`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_hospitals_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `hospital`.`addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`departments` ;

CREATE TABLE IF NOT EXISTS `hospital`.`departments` (
                                                        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                        `title` VARCHAR(45) NOT NULL,
    `department_head_id` BIGINT UNSIGNED NOT NULL,
    `hospital_id` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_departments_hospitals1_idx` (`hospital_id` ASC) VISIBLE,
    INDEX `fk_departments_employees1_idx` (`department_head_id` ASC) VISIBLE,
    CONSTRAINT `fk_departments_hospitals1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `hospital`.`hospitals` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_departments_employees1`
    FOREIGN KEY (`department_head_id`)
    REFERENCES `hospital`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`employees` ;

CREATE TABLE IF NOT EXISTS `hospital`.`employees` (
                                                      `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      `first_name` VARCHAR(45) NOT NULL,
    `last_name` VARCHAR(45) NOT NULL,
    `specialization_id` BIGINT UNSIGNED NOT NULL,
    `department_id` BIGINT UNSIGNED NULL,
    `position` VARCHAR(45) NULL,
    `qualification` INT UNSIGNED NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_workers_specializations1_idx` (`specialization_id` ASC) VISIBLE,
    INDEX `fk_workers_departments1_idx` (`department_id` ASC) VISIBLE,
    CONSTRAINT `fk_workers_specializations1`
    FOREIGN KEY (`specialization_id`)
    REFERENCES `hospital`.`specializations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_workers_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`wards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`wards` ;

CREATE TABLE IF NOT EXISTS `hospital`.`wards` (
                                                  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                  `number` INT UNSIGNED NOT NULL,
                                                  `floor` INT UNSIGNED NOT NULL,
                                                  `department_id` BIGINT UNSIGNED NOT NULL,
                                                  PRIMARY KEY (`id`),
    INDEX `fk_wards_departments1_idx` (`department_id` ASC) VISIBLE,
    CONSTRAINT `fk_wards_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`disease_histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`disease_histories` ;

CREATE TABLE IF NOT EXISTS `hospital`.`disease_histories` (
                                                              `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                              `date` DATE NOT NULL,
                                                              PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`patients` ;

CREATE TABLE IF NOT EXISTS `hospital`.`patients` (
                                                     `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                     `disease_history_id` INT UNSIGNED NOT NULL,
                                                     `ward_id` BIGINT UNSIGNED NOT NULL,
                                                     `first_name` VARCHAR(45) NOT NULL,
    `last_name` VARCHAR(45) NOT NULL,
    `age` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_patients_wards1_idx` (`ward_id` ASC) VISIBLE,
    INDEX `fk_patients_disease_histories1_idx` (`disease_history_id` ASC) VISIBLE,
    CONSTRAINT `fk_patients_wards1`
    FOREIGN KEY (`ward_id`)
    REFERENCES `hospital`.`wards` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_patients_disease_histories1`
    FOREIGN KEY (`disease_history_id`)
    REFERENCES `hospital`.`disease_histories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`department_equipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`department_equipments` ;

CREATE TABLE IF NOT EXISTS `hospital`.`department_equipments` (
                                                                  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                  `department_id` BIGINT UNSIGNED NOT NULL,
                                                                  `equipment_id` BIGINT UNSIGNED NOT NULL,
                                                                  `quantity` INT UNSIGNED NULL,
                                                                  PRIMARY KEY (`id`),
    INDEX `fk_departments_has_equipment_equipment1_idx` (`equipment_id` ASC) VISIBLE,
    INDEX `fk_departments_has_equipment_departments1_idx` (`department_id` ASC) VISIBLE,
    CONSTRAINT `fk_departments_has_equipment_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_departments_has_equipment_equipment1`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `hospital`.`equipments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`department_medications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`department_medications` ;

CREATE TABLE IF NOT EXISTS `hospital`.`department_medications` (
                                                                   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                   `department_id` BIGINT UNSIGNED NOT NULL,
                                                                   `medication_id` BIGINT UNSIGNED NOT NULL,
                                                                   `quantity` INT UNSIGNED NULL,
                                                                   PRIMARY KEY (`id`),
    INDEX `fk_departments_has_medications_medications1_idx` (`medication_id` ASC) VISIBLE,
    INDEX `fk_departments_has_medications_departments1_idx` (`department_id` ASC) VISIBLE,
    CONSTRAINT `fk_departments_has_medications_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_departments_has_medications_medications1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `hospital`.`medications` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`rooms` ;

CREATE TABLE IF NOT EXISTS `hospital`.`rooms` (
                                                  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                  `number` INT NOT NULL,
                                                  PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`appointments` ;

CREATE TABLE IF NOT EXISTS `hospital`.`appointments` (
                                                         `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                         `employee_id` BIGINT UNSIGNED NOT NULL,
                                                         `patient_id` BIGINT UNSIGNED NOT NULL,
                                                         `room_id` INT UNSIGNED NOT NULL,
                                                         `date` DATE NOT NULL,
                                                         PRIMARY KEY (`id`),
    INDEX `fk_appointments_employees1_idx` (`employee_id` ASC) VISIBLE,
    INDEX `fk_appointments_patients1_idx` (`patient_id` ASC) VISIBLE,
    INDEX `fk_appointments_rooms1_idx` (`room_id` ASC) VISIBLE,
    CONSTRAINT `fk_appointments_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hospital`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_appointments_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital`.`patients` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_appointments_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `hospital`.`rooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`diagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`diagnosis` ;

CREATE TABLE IF NOT EXISTS `hospital`.`diagnosis` (
                                                      `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                      `disease_history_id` INT UNSIGNED NOT NULL,
                                                      `title` VARCHAR(45) NOT NULL,
    `description` VARCHAR(45) NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_diagnosis_disease_histories1_idx` (`disease_history_id` ASC) VISIBLE,
    CONSTRAINT `fk_diagnosis_disease_histories1`
    FOREIGN KEY (`disease_history_id`)
    REFERENCES `hospital`.`disease_histories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
