-- MySQL Script generated by MySQL Workbench
-- Mon May  2 20:23:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctors` (
  `idDoctors` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`idDoctors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nurses` (
  `idNurses` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`idNurses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients` (
  `idPatients` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blocks` (
  `idBlocks` INT NOT NULL,
  `floor` INT NOT NULL,
  PRIMARY KEY (`idBlocks`, `floor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `idDepartments` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `chief_physician` INT NOT NULL,
  PRIMARY KEY (`idDepartments`, `chief_physician`),
  INDEX `fk_Departments_Doctors1_idx` (`chief_physician` ASC) VISIBLE,
  CONSTRAINT `fk_Departments_Doctors1`
    FOREIGN KEY (`chief_physician`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Procedures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Procedures` (
  `idProcedures` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `time` DATETIME NULL,
  PRIMARY KEY (`idProcedures`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medications` (
  `idMedications` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `desciption` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedications`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `idRooms` INT NOT NULL,
  `block` INT NOT NULL,
  `floor` INT NOT NULL,
  PRIMARY KEY (`idRooms`, `block`, `floor`),
  CONSTRAINT `fk_Rooms_Blocks1`
    FOREIGN KEY (`block` , `floor`)
    REFERENCES `mydb`.`Blocks` (`idBlocks` , `floor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointments` (
  `idAppointments` INT NOT NULL,
  `patients` INT NOT NULL,
  `doctors` INT NOT NULL,
  PRIMARY KEY (`idAppointments`, `patients`, `doctors`),
  INDEX `fk_Appointments_Patients1_idx` (`patients` ASC) VISIBLE,
  INDEX `fk_Appointments_Doctors1_idx` (`doctors` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_Patients1`
    FOREIGN KEY (`patients`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointments_Doctors1`
    FOREIGN KEY (`doctors`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prescribing_Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prescribing_Medications` (
  `doctor` INT NOT NULL,
  `patient` INT NOT NULL,
  `medications` INT NOT NULL,
  `prescribing` INT NOT NULL,
  PRIMARY KEY (`doctor`, `patient`, `medications`, `prescribing`),
  INDEX `fk_Prescribing_Medications_Patients1_idx` (`patient` ASC) VISIBLE,
  INDEX `fk_Prescribing_Medications_Medications1_idx` (`medications` ASC) VISIBLE,
  INDEX `fk_Prescribing_Medications_Appointments1_idx` (`prescribing` ASC) VISIBLE,
  CONSTRAINT `fk_Prescribing_Medications_Doctors1`
    FOREIGN KEY (`doctor`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescribing_Medications_Patients1`
    FOREIGN KEY (`patient`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescribing_Medications_Medications1`
    FOREIGN KEY (`medications`)
    REFERENCES `mydb`.`Medications` (`idMedications`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescribing_Medications_Appointments1`
    FOREIGN KEY (`prescribing`)
    REFERENCES `mydb`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospitalization` (
  `idHospitalization` INT NOT NULL,
  `room` INT NOT NULL,
  `patient` INT NOT NULL,
  PRIMARY KEY (`idHospitalization`, `room`, `patient`),
  INDEX `fk_Hospitalization_Rooms1_idx` (`room` ASC) VISIBLE,
  INDEX `fk_Hospitalization_Patients1_idx` (`patient` ASC) VISIBLE,
  CONSTRAINT `fk_Hospitalization_Rooms1`
    FOREIGN KEY (`room`)
    REFERENCES `mydb`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospitalization_Patients1`
    FOREIGN KEY (`patient`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operations` (
  `patient` INT NOT NULL,
  `procedure` INT NOT NULL,
  `hospitalization` INT NOT NULL,
  `doctor` INT NOT NULL,
  `nurse` INT NOT NULL,
  PRIMARY KEY (`patient`, `procedure`, `hospitalization`, `doctor`, `nurse`),
  INDEX `fk_Operations_Procedures1_idx` (`procedure` ASC) VISIBLE,
  INDEX `fk_Operations_Hospitalization1_idx` (`hospitalization` ASC) VISIBLE,
  INDEX `fk_Operations_Doctors1_idx` (`doctor` ASC) VISIBLE,
  INDEX `fk_Operations_Nurses1_idx` (`nurse` ASC) VISIBLE,
  CONSTRAINT `fk_Operations_Patients1`
    FOREIGN KEY (`patient`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Procedures1`
    FOREIGN KEY (`procedure`)
    REFERENCES `mydb`.`Procedures` (`idProcedures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Hospitalization1`
    FOREIGN KEY (`hospitalization`)
    REFERENCES `mydb`.`Hospitalization` (`idHospitalization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Doctors1`
    FOREIGN KEY (`doctor`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Nurses1`
    FOREIGN KEY (`nurse`)
    REFERENCES `mydb`.`Nurses` (`idNurses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nurse_Call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nurse_Call` (
  `nurse` INT NOT NULL,
  `block` INT NOT NULL,
  `floor` INT NOT NULL,
  `room` INT NOT NULL,
  PRIMARY KEY (`nurse`, `block`, `floor`, `room`),
  INDEX `fk_Nurse_Call_Blocks1_idx` (`block` ASC, `floor` ASC) VISIBLE,
  INDEX `fk_Nurse_Call_Rooms1_idx` (`room` ASC) VISIBLE,
  INDEX `fk_Nurse_Call_Nurses1_idx` (`nurse` ASC) VISIBLE,
  CONSTRAINT `fk_Nurse_Call_Blocks1`
    FOREIGN KEY (`block` , `floor`)
    REFERENCES `mydb`.`Blocks` (`idBlocks` , `floor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurse_Call_Rooms1`
    FOREIGN KEY (`room`)
    REFERENCES `mydb`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurse_Call_Nurses1`
    FOREIGN KEY (`nurse`)
    REFERENCES `mydb`.`Nurses` (`idNurses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treatment_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treatment_Data` (
  `doctors_idDoctors` INT NOT NULL,
  `patients_idPatients` INT NOT NULL,
  `diagnosis` VARCHAR(45) NULL,
  PRIMARY KEY (`doctors_idDoctors`, `patients_idPatients`),
  INDEX `fk_Doctors_has_Patients_Patients1_idx` (`patients_idPatients` ASC) VISIBLE,
  INDEX `fk_Doctors_has_Patients_Doctors_idx` (`doctors_idDoctors` ASC) VISIBLE,
  CONSTRAINT `fk_Doctors_has_Patients_Doctors`
    FOREIGN KEY (`doctors_idDoctors`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctors_has_Patients_Patients1`
    FOREIGN KEY (`patients_idPatients`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admission_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admission_Data` (
  `appointments` INT NOT NULL,
  `doctors` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`appointments`, `doctors`),
  INDEX `fk_Appointments_has_Doctors_Doctors1_idx` (`doctors` ASC) VISIBLE,
  INDEX `fk_Appointments_has_Doctors_Appointments1_idx` (`appointments` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_has_Doctors_Appointments1`
    FOREIGN KEY (`appointments`)
    REFERENCES `mydb`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointments_has_Doctors_Doctors1`
    FOREIGN KEY (`doctors`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
