-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 15:21:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctors` (
  `idDoctors` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NULL,
  PRIMARY KEY (`idDoctors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nurses` (
  `idNurses` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNurses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients` (
  `idPatients` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blocks` (
  `idBlocks` INT NOT NULL,
  `Floor` INT NOT NULL,
  PRIMARY KEY (`idBlocks`, `Floor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `idDepartments` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Chief_Physician` INT NOT NULL,
  PRIMARY KEY (`idDepartments`, `Chief_Physician`),
  INDEX `fk_Departments_Doctors1_idx` (`Chief_Physician` ASC) VISIBLE,
  CONSTRAINT `fk_Departments_Doctors1`
    FOREIGN KEY (`Chief_Physician`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Procedures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Procedures` (
  `idProcedures` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idProcedures`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medications` (
  `idMedications` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Desciption` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedications`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `idRooms` INT NOT NULL,
  `Block` INT NOT NULL,
  `Floor` INT NOT NULL,
  PRIMARY KEY (`idRooms`, `Block`, `Floor`),
  CONSTRAINT `fk_Rooms_Blocks1`
    FOREIGN KEY (`Block` , `Floor`)
    REFERENCES `mydb`.`Blocks` (`idBlocks` , `Floor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointments` (
  `idAppointments` INT NOT NULL,
  `Patients` INT NOT NULL,
  `Doctors` INT NOT NULL,
  PRIMARY KEY (`idAppointments`, `Patients`, `Doctors`),
  INDEX `fk_Appointments_Patients1_idx` (`Patients` ASC) VISIBLE,
  INDEX `fk_Appointments_Doctors1_idx` (`Doctors` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_Patients1`
    FOREIGN KEY (`Patients`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointments_Doctors1`
    FOREIGN KEY (`Doctors`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prescribing_Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prescribing_Medications` (
  `Doctor` INT NOT NULL,
  `Patient` INT NOT NULL,
  `Medications` INT NOT NULL,
  `Prescribing` INT NOT NULL,
  PRIMARY KEY (`Doctor`, `Patient`, `Medications`, `Prescribing`),
  INDEX `fk_Prescribing_Medications_Patients1_idx` (`Patient` ASC) VISIBLE,
  INDEX `fk_Prescribing_Medications_Medications1_idx` (`Medications` ASC) VISIBLE,
  INDEX `fk_Prescribing_Medications_Appointments1_idx` (`Prescribing` ASC) VISIBLE,
  CONSTRAINT `fk_Prescribing_Medications_Doctors1`
    FOREIGN KEY (`Doctor`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescribing_Medications_Patients1`
    FOREIGN KEY (`Patient`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescribing_Medications_Medications1`
    FOREIGN KEY (`Medications`)
    REFERENCES `mydb`.`Medications` (`idMedications`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescribing_Medications_Appointments1`
    FOREIGN KEY (`Prescribing`)
    REFERENCES `mydb`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospitalization` (
  `idHospitalization` INT NOT NULL,
  `Room` INT NOT NULL,
  `Patient` INT NOT NULL,
  PRIMARY KEY (`idHospitalization`, `Room`, `Patient`),
  INDEX `fk_Hospitalization_Rooms1_idx` (`Room` ASC) VISIBLE,
  INDEX `fk_Hospitalization_Patients1_idx` (`Patient` ASC) VISIBLE,
  CONSTRAINT `fk_Hospitalization_Rooms1`
    FOREIGN KEY (`Room`)
    REFERENCES `mydb`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospitalization_Patients1`
    FOREIGN KEY (`Patient`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operations` (
  `Patient` INT NOT NULL,
  `Procedure` INT NOT NULL,
  `Hospitalization` INT NOT NULL,
  `Doctor` INT NOT NULL,
  `Nurse` INT NOT NULL,
  PRIMARY KEY (`Patient`, `Procedure`, `Hospitalization`, `Doctor`, `Nurse`),
  INDEX `fk_Operations_Procedures1_idx` (`Procedure` ASC) VISIBLE,
  INDEX `fk_Operations_Hospitalization1_idx` (`Hospitalization` ASC) VISIBLE,
  INDEX `fk_Operations_Doctors1_idx` (`Doctor` ASC) VISIBLE,
  INDEX `fk_Operations_Nurses1_idx` (`Nurse` ASC) VISIBLE,
  CONSTRAINT `fk_Operations_Patients1`
    FOREIGN KEY (`Patient`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Procedures1`
    FOREIGN KEY (`Procedure`)
    REFERENCES `mydb`.`Procedures` (`idProcedures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Hospitalization1`
    FOREIGN KEY (`Hospitalization`)
    REFERENCES `mydb`.`Hospitalization` (`idHospitalization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Doctors1`
    FOREIGN KEY (`Doctor`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operations_Nurses1`
    FOREIGN KEY (`Nurse`)
    REFERENCES `mydb`.`Nurses` (`idNurses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nurse_Call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nurse_Call` (
  `Nurse` INT NOT NULL,
  `Block` INT NOT NULL,
  `Floor` INT NOT NULL,
  `Room` INT NOT NULL,
  PRIMARY KEY (`Nurse`, `Block`, `Floor`, `Room`),
  INDEX `fk_Nurse_Call_Blocks1_idx` (`Block` ASC, `Floor` ASC) VISIBLE,
  INDEX `fk_Nurse_Call_Rooms1_idx` (`Room` ASC) VISIBLE,
  INDEX `fk_Nurse_Call_Nurses1_idx` (`Nurse` ASC) VISIBLE,
  CONSTRAINT `fk_Nurse_Call_Blocks1`
    FOREIGN KEY (`Block` , `Floor`)
    REFERENCES `mydb`.`Blocks` (`idBlocks` , `Floor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurse_Call_Rooms1`
    FOREIGN KEY (`Room`)
    REFERENCES `mydb`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurse_Call_Nurses1`
    FOREIGN KEY (`Nurse`)
    REFERENCES `mydb`.`Nurses` (`idNurses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treatment_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treatment_Data` (
  `Doctors_idDoctors` INT NOT NULL,
  `Patients_idPatients` INT NOT NULL,
  `Diagnosis` VARCHAR(45) NULL,
  PRIMARY KEY (`Doctors_idDoctors`, `Patients_idPatients`),
  INDEX `fk_Doctors_has_Patients_Patients1_idx` (`Patients_idPatients` ASC) VISIBLE,
  INDEX `fk_Doctors_has_Patients_Doctors_idx` (`Doctors_idDoctors` ASC) VISIBLE,
  CONSTRAINT `fk_Doctors_has_Patients_Doctors`
    FOREIGN KEY (`Doctors_idDoctors`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctors_has_Patients_Patients1`
    FOREIGN KEY (`Patients_idPatients`)
    REFERENCES `mydb`.`Patients` (`idPatients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admission_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admission_Data` (
  `Appointments` INT NOT NULL,
  `Doctors` INT NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Appointments`, `Doctors`),
  INDEX `fk_Appointments_has_Doctors_Doctors1_idx` (`Doctors` ASC) VISIBLE,
  INDEX `fk_Appointments_has_Doctors_Appointments1_idx` (`Appointments` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_has_Doctors_Appointments1`
    FOREIGN KEY (`Appointments`)
    REFERENCES `mydb`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointments_has_Doctors_Doctors1`
    FOREIGN KEY (`Doctors`)
    REFERENCES `mydb`.`Doctors` (`idDoctors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
